@startuml
actor Пользователь
participant "API Gateway" as gateway
participant "Redis (кэш is_premium)" as redis
participant "Playback Service" as playback
participant "Kafka" as kafka
participant "Ads Service" as ads
participant "Object Storage (S3/CDN)" as cdn
participant "Events Statistics Service" as stats

Пользователь -> gateway: GET /stream/{track_id} (JWT)
gateway -> redis: Проверка is_premium по user_id
redis --> gateway: false (free аккаунт)

gateway -> playback: GET /stream/{track_id}
playback -> cdn: Запрос pre-signed URL
cdn --> playback: Возврат аудио URL

playback -> kafka: Publish PlaybackStarted
kafka -> stats: Consume PlaybackStarted (сбор аналитики)
kafka -> recommendations: Consume PlaybackStarted (учёт в подборке рекомендаций)

playback --> gateway: audio_url

gateway -> ads: GET /ad
ads --> gateway: ad_url (a/v креатив)

gateway --> Пользователь: { audio_url, ad_url, interval=420s }

note right of Пользователь
  Плеер сначала проигрывает рекламу,
  затем трек. Через 7 минут — повторная вставка рекламы.
end note
@enduml